name: Build, Test & Analyse

on:
  pull_request:
    branches: [ master, main ]

jobs:
  concourse-build-check:
    name: Concourse Build Check
    uses: DNAstack/dnastack-development-tools/.github/workflows/concourse-build-check.yml@64794af481d05458b83f41da1ec55fde2487e0f4
    with:
      pipeline_name: 'publisher-dev'
      job_name: 'setup-dnastack-client-library-e2e-test-client'
      concourse_username: ${{ vars.CONCOURSE_USERNAME }}
    secrets:
      concourse_password: ${{ secrets.CONCOURSE_PASSWORD }}
